spring:
  application:
    name: jwt_code_practice
  config:
    import:
      - optional:file:.env[.properties]
  profiles:
    group:
      dev: ["dev_auth", "dev_db", "dev_server"]
    active: dev
logging:
  level:
    root: info
